### ISSUE TITLE
Update node version to 18

### ISSUE THREAD

**Issue by SnailBones** [maplibre/maplibre-gl-js-docs#390]
[Maplibre gl js](https://github.com/maplibre/maplibre-gl-js/blob/main/CONTRIBUTING.md) use Node 18. Upgrading this repo to the same will expedite switching and encourage more docs contributions, and may help to merge the repos as in https://github.com/maplibre/maplibre-gl-js/issues/2150.

**Comment by HarelM** [comment]
Generally speaking, you are right.
But we are looking into moving this repo into maplibre-gl-js, so this won't be needed.
It's also currently broken due to changes in maplibre-gl-js so we still need to take care of that first...

**Comment by birkskyum** [comment]
This is already node 18 compatible AFAIK - Remember working on that half a year ago.

**Comment by SnailBones** [comment]
Interesting, I'm seeing the following error on `npm run start`. with node v18.13.0.

Maybe this is platform specific? i"m on Ubuntu.
```
npm ERR! command sh -c -- prebuild-install || node-gyp rebuild
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.13.0 runtime=node arch=x64 libc= platform=linux)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.13.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/ailanthus/Documents/maplibre-gl-js-docs/maplibre-gl-js/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ailanthus/Documents/maplibre-gl-js-docs/maplibre-gl-js/node_modules/gl/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ailanthus/Documents/maplibre-gl-js-docs/maplibre-gl-js/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ailanthus/.cache/node-gyp/18.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ailanthus/.cache/node-gyp/18.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/ailanthus/Documents/maplibre-gl-js-docs/maplibre-gl-js/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ailanthus/.cache/node-gyp/18.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/ailanthus/Documents/maplibre-gl-js-docs/maplibre-gl-js/node_modules/gl',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: python: not found
npm ERR! gyp: Call to 'python commit_id.py check ..' returned exit status 127 while in angle/src/angle.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/ailanthus/Documents/maplibre-gl-js-docs/maplibre-gl-js/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.15.0-58-generic
npm ERR! gyp ERR! command "/home/ailanthus/.nvm/versions/node/v18.13.0/bin/node" "/home/ailanthus/Documents/maplibre-gl-js-docs/maplibre-gl-js/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/ailanthus/Documents/maplibre-gl-js-docs/maplibre-gl-js/node_modules/gl
npm ERR! gyp ERR! node -v v18.13.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ailanthus/.npm/_logs/2023-02-19T14_55_38_472Z-debug-0.log
ERROR: "install-gl-js-deps" exited with 1.
```

**Comment by HarelM** [comment]
Looks like python is missing for gyp...?

**Comment by SnailBones** [comment]
> Looks like python is missing for gyp...?

@HarelM You're correct, and I was able to resolve that issue.  After installing `@type/node` as a dev dependency to fix another issue, I'm now seeing:

```
[11:36:32 Batfish] Starting the development server.
[11:36:32 Batfish] Wait ...
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/ailanthus/Documents/maplibre-gl-js-docs/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/ailanthus/Documents/maplibre-gl-js-docs/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/ailanthus/Documents/maplibre-gl-js-docs/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/ailanthus/Documents/maplibre-gl-js-docs/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/ailanthus/Documents/maplibre-gl-js-docs/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/ailanthus/Documents/maplibre-gl-js-docs/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/ailanthus/Documents/maplibre-gl-js-docs/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/ailanthus/Documents/maplibre-gl-js-docs/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

This error is discussed on this [Slack Overflow page](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported). I've tried the suggested `npm audit fix --force`, unfortunately this leads to TypeScript errors that seem to require substantial refactoring to fix.

**Comment by birkskyum** [comment]
This one can be fixed by copying the environmental variables in the npm run start script to also be in the npm run build

**Comment by SnailBones** [comment]
> This "digital envelope" error can be fixed by copying the environmental variables in the npm run start script to also be in the npm run build. Specifically the NODE_OPTION about legacy ssl


Thanks @birkskyum! Now I'm seeing this error:

```
[14:50:23 Batfish] Error: Webpack compilation error.

./node_modules/@maplibre/maplibre-gl-style-spec/tsc/src/reference/latest.js 1:27
Module parse failed: Unexpected token (1:27)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
> import spec from'./v8.json'assert{type:'json'};export default spec;

[14:50:23 Batfish] Webpack compiled in 1m 5.1s
[14:50:26 Batfish] Error: Webpack compilation error.

```

**Comment by birkskyum** [comment]
I believe you need to remove the "assert{type:'json'}" like we do here as well https://github.com/maplibre/maplibre-gl-js-docs/blob/main/remove-assert.js

**Comment by birkskyum** [comment]
Assert type JSON is such a mess that it was recently downgraded from level 3 to level 2, so it's now undecided again if it will be part of the language, or at least how it will be implemented
